# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (english'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title (english'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(through='gallery.GalleryMediaFile', to='medialibrary.MediaFile', verbose_name='Gallery Images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
