# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20161108_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title (english)'),
        ),
    ]
