# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170209_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='internal_name',
        ),
    ]
