# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170216_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='internal_name',
            field=models.CharField(help_text='Erscheint nicht auf der Website', max_length=500, verbose_name='Interne Bezeichnung'),
        ),
    ]
