# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0009_auto_20161031_1305'),
        ('gallery', '0005_auto_20170216_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='background_color',
            field=models.ForeignKey(blank=True, help_text='Wird angezeigt, bevor das erste Bild geladen wird', null=True, on_delete=django.db.models.deletion.CASCADE, to='billboard.Color', verbose_name='Hintergrundfarbe'),
        ),
    ]
